name: "Streaming Camera Cover Detection"
description: "Detects QR codes in an IP camera stream and sends Cover events to Home Assistant"
version: "0.0.2"
slug: "ha_cam_cover"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  entity_id: "sensor.garage_door"
  camera_rtsp_stream: "http://192.168.1.200/cgi-bin/jpeg.cgi"
  loop_time: "30"
schema:
  entity_id: "match(^[a-zA-Z]+\\.[a-zA-Z0-9_-]+$)"
  camera_rtsp_stream: "match(^https{0,1}:\/\/.*)"
  loop_time: "match([0-9]+)"
